### ISSUE TITLE
Clicking on links with a "javascript:some_function()"-url loads to an error.

### ISSUE THREAD

**Issue by phseiff** [Gusted/darkreader-web#8]
Clicking on a link `<a href="https://foo.com">` in a displayed website leads to `https://darkreader-web.vercel.app/?url=https://foo.com`.
This is obviously intended behavior, but clicking on a link like `<a href="javascript:some_function()">` leads to [https://darkreader-web.vercel.app/?url=javascript:some_function()](https://darkreader-web.vercel.app/?url=javascript:some_function()), which yields an error (see the link or screenshot). You can, for example, see this effect in the wild if you visit [my website](https://phseiff.com) and click on the header.

The error page looks somewhat like this (I believe this is an error in the backend, so it should probably be fixable without running into cross-origin request problems, I think?):

![image](https://user-images.githubusercontent.com/31518703/109390481-3164e480-7912-11eb-9675-a936f627741d.png)

**Comment by Gusted** [comment]
Thanks for letting me know! didn't knew that was possible as well.

**Comment by phseiff** [comment]
Sorry for nitpicking, but the comment in your commit
> Firefox puts an incorrect href into element.href which doesn't correspondent to the attribute href and isn't relative to main url.
is, as far as I understand it, not the actual cause of this problem (though your commit certainly fixes it).

`javascript:`-hrefs are actually supported by any browser, just like `mailto:`-hrefs and `tel:`-hrefs (see [here](https://www.w3schools.com/tags/att_a_href.asp)). The issue wasn't that Firefox changed the href-Attribute, it was that the href-Attribute specifies a function to be called rather than a link to be followed.

You might have noticed that the served html of my website (which I used as an example in my issue) does not contain any `"javascript:"`-hrefs, but that is because my website modifies its own href-attributes at runtime via javascript and not because Firefox modified `element.href` in a way which makes it nonconforming to the attribute href. A site which doesn't do this, yet still decides to use a `javascript`-href, would've had the same issue, regardless of the browser it runs in.

On a related note, I noticed that `tel:`-hrefs (see [here](https://darkreader-web.vercel.app/?url=https://www.desjardinsgeneralinsurance.com/)) as well as `mailto:`-hrefs don't work either (see [here](https://darkreader-web.vercel.app/?url=https://www.bloomclass.com/)).

I quickly created a pull request that hopefully fixes this.

**Comment by Gusted** [comment]
Hi @phseiff!

That comment wasn't necessarily to that commit, I simply moved that comment, because I moved the `getAttribute('href')`.
As you can see it never got added or removed, due git thinking other lines could be better to see as add/removed.

The issue that caused it for me to place it their, was due elements which are relative e.g.
`<a href="v9_16/">` and you are on https://darkreader.org/blog` when clicking the url changes to https://darkreader.org/blog/v9_16/, funny thing is when you use the `.href` property you get https://darkreader.org/v9_16 returned which isn't relative to the current url. However when getting the raw `href` content, I steal some logic from Dark Reader to retrieve the correct absolute URL, because it might seem weird on the first eye to use getAttribute I'd placed that comment their. Not related to this problem.

**Comment by phseiff** [comment]
@Gusted Thanks for the explanation, that clears up my confusion. 👍
